on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7', '3.0' ]
    name: ${{ matrix.ruby }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      run: |
        gem install bundler
        bundle install
        rspec
