on:
  push:
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7', '3.0' ]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.ruby }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: rspec
